"""add assessment_type to services

Revision ID: c51e88d4dd94
Revises: 8f7da0b791cf
Create Date: 2026-06-06 09:21:06.979487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51e88d4dd94'
down_revision: Union[str, Sequence[str], None] = '8f7da0b791cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('assessment_type', sa.Enum('none', 'brainmap', 'remap', name='assessmenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'assessment_type')
    # ### end Alembic commands ###
